apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - name: app-port
      port: 8084
      targetPort: 8084
      protocol: TCP
      nodePort: 30084
    - name: debug-port
      port: 5084
      targetPort: 5084
      protocol: TCP
      nodePort: 30584
  type: NodePort