apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - name: app-port
      port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 30082
    - name: debug-port
      port: 5082
      targetPort: 5082
      protocol: TCP
      nodePort: 30582
  type: NodePort